kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: openshift-gitops-openshift-gitops-argocd-application-controller-additonal
  labels:
    app.kubernetes.io/instance: openshift-gitops
rules:
  - verbs:
      - '*'
    apiGroups:
      - ""
    resources:
      - secrets
  - verbs:
      - '*'
    apiGroups:
      - ""
    resources:
      - serviceaccounts
  - verbs:
      - '*'
    apiGroups:
      - "integreatly.org"
    resources:
      - grafanadatasources
  - verbs:
      - '*'
    apiGroups:
      - "integreatly.org"
    resources:
      - grafanas
  - verbs:
      - '*'
    apiGroups:
      - "batch"
    resources:
      - jobs
  - verbs:
      - '*'
    apiGroups:
      - "logging.openshift.io"
    resources:
      - elasticsearches
      - ClusterLogging
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: gitops-additonal-rbac
  labels:
    app.kubernetes.io/instance: openshift-gitops
subjects:
  - kind: ServiceAccount
    name: openshift-gitops-argocd-application-controller
    namespace: openshift-gitops
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: openshift-gitops-openshift-gitops-argocd-application-controller-additonal